# Generated by Django 6.0 on 2025-12-10 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('average_daily_passengers', models.PositiveIntegerField(default=0, help_text='Nombre moyen de passagers par jour. Sert à calculer le nombre de comptoirs nécessaires.')),
            ],
            options={
                'verbose_name': 'Compagnie aérienne',
                'verbose_name_plural': 'Compagnies aériennes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prefix', models.CharField(default='A', help_text='Préfixe pour les tickets (ex: A, B, C)', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A1', 'Comptoir A1'), ('A2', 'Comptoir A2'), ('A3', 'Comptoir A3'), ('A4', 'Comptoir A4'), ('A5', 'Comptoir A5'), ('A6', 'Comptoir A6'), ('A7', 'Comptoir A7'), ('A8', 'Comptoir A8'), ('A9', 'Comptoir A9'), ('A10', 'Comptoir A10'), ('A11', 'Comptoir A11'), ('A12', 'Comptoir A12'), ('B1', 'Comptoir B1'), ('B2', 'Comptoir B2'), ('B3', 'Comptoir B3'), ('B4', 'Comptoir B4'), ('B5', 'Comptoir B5'), ('B6', 'Comptoir B6'), ('B7', 'Comptoir B7'), ('B8', 'Comptoir B8'), ('B9', 'Comptoir B9'), ('B10', 'Comptoir B10'), ('B11', 'Comptoir B11'), ('B12', 'Comptoir B12')], help_text='Identifiant physique (Ex: A1, B12)', max_length=5, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_counters', to='api.company')),
            ],
            options={
                'verbose_name': 'Comptoir',
                'verbose_name_plural': 'Comptoirs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('ON_TIME', "À l'heure"), ('DELAYED', 'Retardé'), ('CANCELLED', 'Annulé'), ('BOARDING', 'Embarquement')], default='ON_TIME', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='api.company')),
            ],
            options={
                'verbose_name': 'Vol',
                'verbose_name_plural': 'Vols',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(help_text='Numéro de vol saisi par le passager (ex: AF480)', max_length=20)),
                ('queue_number', models.CharField(blank=True, editable=False, help_text="Numéro unique généré pour l'appel (Ex: A001)", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('WAITING', 'En attente'), ('CALLED', 'Appelé'), ('DONE', 'Terminé'), ('CANCELLED', 'Annulé')], default='WAITING', max_length=20)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='api.counter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.service')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['created_at'],
            },
        ),
    ]
