# Generated by Django 6.0 on 2025-12-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='status',
        ),
        migrations.AddField(
            model_name='company',
            name='average_service_time_minutes',
            field=models.PositiveIntegerField(default=3, help_text='Temps de service moyen par voyageur (en minutes) (T_moyen).'),
        ),
        migrations.AddField(
            model_name='counter',
            name='status',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCCUPE', 'Occupé'), ('FERME', 'Fermé')], default='LIBRE', help_text="Statut d'occupation du comptoir.", max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='estimated_waiting_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text="Temps d'attente estimé à l'enregistrement (en minutes)."),
        ),
        migrations.AlterField(
            model_name='company',
            name='average_daily_passengers',
            field=models.PositiveIntegerField(default=0, help_text='Nombre moyen de passagers par jour.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='queue_number',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(help_text='Numéro de vol saisi par le passager', max_length=20),
        ),
    ]
