# Generated by Django 6.0 on 2025-12-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_counter_is_active_remove_flight_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('ON_TIME', "À l'heure"), ('DELAYED', 'Retardé'), ('CANCELLED', 'Annulé'), ('BOARDING', 'Embarquement')], default='ON_TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='average_service_time_minutes',
            field=models.PositiveIntegerField(default=3, help_text='Temps de service moyen par voyageur (en minutes).'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, help_text='Code IATA (Ex: AF, ET)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='queue_number',
            field=models.CharField(blank=True, editable=False, help_text="Numéro unique généré pour l'appel (Ex: A001)", max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(help_text='Numéro de vol saisi par le passager (ex: AF480)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('flight_number', 'departure_time')},
        ),
    ]
